#! /usr/bin/python

import sys
from string import whitespace

#Alex Hortin
#Computer Science 483
#
#This program is made to isolate facebook chat packets and display them 
#using an input of a .cap file generated by Wireshark or Airodump.  It 
#works on any unencrypted network

    
if len(sys.argv) >1:
	input_file = file(sys.argv[1], 'r')
else:
	print "...please supply an input file"
	exit(1)
convos = []

userlist = {  }
    
for line in input_file:
	linepot = line.split('\"')
	for i in range(len(linepot)):
		if i >= 6:
			if linepot[i] == "from" and linepot[i-1] == "},":
				fromid = linepot[i+1][1:-1]
				toid = linepot[i+3][1:-1]
				fromname = linepot[i+6]
				toname = linepot[i+10]
				msg = linepot[i-10]
				msgid = linepot[i-1]                    
				print fromname,"ID# (",fromid,") to ",toname,"ID# (",toid,")\n\"",msg,"\"\n"                              
input_file.close()                

#input_file = file(sys.argv[1], 'r')
#for line in input_file:
#    linepot = line.split('=')
#    for i in range(len(linepot)):
#        if linepot[i][-6:] == "php?id":
#            viewed = linepot[i+1][:-4]
#            print "viewed", viewed 
        #if linepot[i][-8:] == "; c_user":
            #print linepot[i+1][:-8]





#If an output file is specified write the output here
if len(sys.argv) >2:
	FILE = open(sys.argv[2],"w")
	FILE.writelines(tofile)
    





